#### app configs
app:
   kafka:
      listener:
         topic: PAYMENT_INIT
         group-id: group-id
   
#### spring context configs
spring:
   application:
      name: payment-clearing-ms
   kafka:
     bootstrap-servers: localhost:9092
     consumer:
        group-id: group-id
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer  
        properties:
           spring:
             json:
               value:
                 default:
                   type: 'com.paymen.core.message.producer.vo.Envelop'
               type:
                 mapping: 'com.paymen.core.message.producer.vo.Envelop:com.paymen.core.message.producer.vo.Envelop'
               trusted:
                 packages: 'com.paymen.core.message.producer.vo'

server:
   port: 9004

#### eureka registry configs
eureka:
   instance:
      hostname: 192.168.0.11
      preferIpAddress: true
   client:
      service-url:
         defaultZone: http://192.168.0.11:8761/eureka
         
#### spring  configs server
#spring.config.import=configserver:http://localhost:8888

